var gvjs_33="unique",gvjs_43="sankey.node.label.unselected",gvjs_53="sankey.node.label.unfocused",gvjs_63="sankey.node.label.selected",gvjs_73="sankey.node.label.focused",gvjs_83="sankey.node.color.unselected",gvjs_93="sankey.node.color.unfocused",gvjs_$3="sankey.node.color.selected",gvjs_a4="sankey.node.color.focused",gvjs_b4="sankey.link.color.unselected",gvjs_c4="sankey.link.color.unfocused",gvjs_d4="sankey.link.color.selected",gvjs_e4="sankey.link.color.focused";function gvjs_f4(a,b){gvjs_lU.call(this);this.ta=null;this.Xi=b;this.YI=null;this.G2=new gvjs_A;this.E2=new gvjs_A;this.xa=a}gvjs_p(gvjs_f4,gvjs_lU);
gvjs_f4.prototype.CB=function(a){var b=[],c=gvjs_MM(a.gb());this.ta&&(this.xa.Eg?gvjs_XJ(this.ta,this.Xi.getContainer()):b.push(new gvjs_kU(gvjs_ZJ(this.ta,c).j(),new gvjs_OM(gvjs_0T),gvjs_0l)),this.ta=null);var d=new gvjs_A,e=new gvjs_A,f=new gvjs_A,g=new gvjs_A;null!=this.YI&&gvjs_tma(this,this.YI,e,d);gvjs_ch(this.E2,function(a){var b=this.xa.paths[a];f.add(a);g.add(b.uY);g.add(b.B4)},this);gvjs_ch(this.G2,function(a){gvjs_g4(this,a,f,g)},this);var h=0<g.Eb(),k=0<d.Eb();gvjs_q(this.xa.labels,function(a,
e){var f=a.styles.Zd,l=gvjs_VT;g.contains(e)&&d.contains(e)?(f=a.styles.$K,l=gvjs_Et):d.contains(e)?f=a.styles.focused:g.contains(e)?(f=a.styles.selected,l=gvjs_Et):h&&k?f=a.styles.aM:h?f=a.styles.$L:k&&(f=a.styles.ZL);a=c.Ls(a.text,a.x,a.y,a.width,a.angle,a.aA,a.bA,f);e=gvjs_QM(gvjs_QM(new gvjs_OM(gvjs_0s),gvjs_rt,e),gvjs_ut,gvjs_Rw);b.push(new gvjs_kU(a,e,l))},this);gvjs_q(this.xa.oS,function(a,e){var f=gvjs_QM(gvjs_QM(gvjs_PM(e),gvjs_ut,"node"),"NAME",this.xa.labels[e].text),l=a.cc.Zd,m=gvjs_VT;
g.contains(e)&&d.contains(e)?(l=a.cc.$K,m=gvjs_RT):d.contains(e)?l=a.cc.focused:g.contains(e)?(m=gvjs_RT,l=a.cc.selected):h&&k?l=a.cc.aM:h?l=a.cc.$L:k&&(l=a.cc.ZL);a=c.em(a.x,a.y,a.width,a.height,l);b.push(new gvjs_kU(a,f,m))},this);var l=0<f.Eb(),m=0<e.Eb();gvjs_q(this.xa.paths,function(a,d){var g=gvjs_QM(gvjs_QM(new gvjs_OM(gvjs_qt),gvjs_rt,d),gvjs_ut,"link"),h=a.cc.Zd,k=gvjs_oy;f.contains(d)&&e.contains(d)?(h=a.cc.$K,k=gvjs_RT):e.contains(d)?h=a.cc.focused:f.contains(d)?(k=gvjs_RT,h=a.cc.selected):
l&&m?h=a.cc.aM:l?h=a.cc.$L:m&&(h=a.cc.ZL);a=c.Sc(a.Nc,h);b.push(new gvjs_kU(a,g,k))},this);return b};gvjs_f4.prototype.gc=function(){return this.xa.size};function gvjs_tma(a,b,c,d){var e=b.xb.SUBTYPE;null!=a.YI&&(b=a.YI.xb.ROW_INDEX,"node"===e?gvjs_g4(a,b,c,d):"link"===e&&(a=a.xa.paths[b],c.add(b),d.add(a.uY),d.add(a.B4)))}function gvjs_g4(a,b,c,d){d.add(b);gvjs_q(a.xa.Zta[b].Ra(),function(a){c.add(a);a=this.xa.paths[a];d.add(a.uY);d.add(a.B4)},a)}
gvjs_f4.prototype.Rm=function(a,b,c){switch(b.type){case gvjs_0l:a.type()===gvjs_qt?this.dz(a,c):a.type();break;case gvjs_gk:a.type()===gvjs_qt?this.YI=c?a:null:a.type();break;case gvjs_J:a.type()===gvjs_qt&&(b=a.xb.ROW_INDEX,"node"===a.xb.SUBTYPE?c?this.G2.add(b):this.G2.remove(b):c?this.E2.add(b):this.E2.remove(b))}};
gvjs_f4.prototype.dz=function(a,b){this.Xi.clear();this.ta=null;if(b){b=a.xb.SUBTYPE;var c=a.xb.ROW_INDEX;a=this.xa.size;a=new gvjs_y(0,a.width,a.height,0);var d=null,e=null,f=null,g=null;"node"==b?(g=this.xa.oS[c],e=new gvjs_v(g.x,g.y),f=gvjs_Mf(e,new gvjs_v(-1,1))):"link"==b&&(g=this.xa.paths[c],b=g.Nc,e=new gvjs_v((b.Nc[0].data.x+b.Nc[1].data.x)/2,(b.Nc[0].data.y+b.Nc[1].data.y)/2),f=gvjs_Mf(e,new gvjs_v(-1,1)));g.ya&&e&&f&&(g.ya.content&&this.xa.Eg?d={html:{name:gvjs_db,content:g.ya.content,properties:{className:gvjs_cw}},
AH:g.ya.Fi,qK:f,anchor:e,GG:a,spacing:20,margin:5}:(b={entries:[]},g.ya.content?b.entries.push(gvjs_3E(g.ya.content,this.xa.Xp)):g.ya.title&&(b.entries.push(gvjs_3E(g.ya.title,this.xa.Xp)),b.entries.push(gvjs_3E(g.ya.Lya.toString(),this.xa.Xp,g.ya.Jya,this.xa.Xp)),g.ya.Nda&&g.ya.Oda&&b.entries.push(gvjs_3E(g.ya.Oda.toString(),this.xa.Xp,g.ya.Nda,this.xa.Xp))),d=gvjs_6E(b,this.xa.Oc,!1,e,a,f,void 0,this.xa.Eg)));d&&(this.ta=d)}};var gvjs_uma={NONE:gvjs_d,oFa:"source",JFa:"target",ICa:gvjs_lb},gvjs_vma={YU:gvjs_Gu,cGa:gvjs_33};function gvjs_h4(a,b,c,d){this.J=a;this.m=b;this.me=c;this.ib=d;this.lb=(new gvjs_Gq).Qc(a);this.Cta=gvjs_E(b,"sankey.iterations");this.fca=gvjs_Qi(b,"sankey.link.color");gvjs_Qi(b,"sankey.link.focused");gvjs_Qi(b,"sankey.link.unfocused");a=b.cD("sankey.link.colors");this.gca=null==a?null:gvjs_r(a,function(a){return gvjs_rd(gvjs_ld(a).hex)});this.zD=gvjs_C(b,"sankey.link.colorMode",gvjs_d,gvjs_uma);this.xna=gvjs_E(b,"sankey.link.defaultOpacity",this.fca.ff);this.Qca=gvjs_E(b,"sankey.link.minOpacity",
.2);this.qua=gvjs_E(b,"sankey.link.maxOpacity",.6);a=b.cD("sankey.node.colors");this.eva=null==a?null:gvjs_r(a,function(a){return gvjs_rd(gvjs_ld(a).hex)});this.dva=gvjs_Qi(b,"sankey.node.color");this.P0=gvjs_C(b,"sankey.node.colorMode",gvjs_33,gvjs_vma);this.TP=gvjs_D(b,gvjs_uw,!1);this.lf=gvjs_Ri(b,"sankey.node.label");this.Pba=gvjs_E(b,"sankey.node.labelPadding");this.fva=gvjs_E(b,"sankey.node.nodePadding");this.gva=gvjs_E(b,"sankey.node.width")}
gvjs_h4.prototype.Jh=function(){var a=gvjs_wma(this);gvjs_xma(a);var b=this.lf.fontSize;b=d3.sankey().nodeWidth(this.gva).nodePadding(this.fva).size([this.ib.width,this.ib.height-b/2]).iterations(this.Cta);b(a);gvjs_yma(a.nodes);var c=new gvjs_yU(this.TP,this.eva),d=new gvjs_yU(this.TP,this.gca),e=[],f=[],g=[],h=null==this.gca&&this.P0===gvjs_33;gvjs_q(a.nodes,function(a,b){a.idx=b;c.Ju(this.P0===gvjs_Gu?a.Lb:String(b));h||("source"===this.zD&&0<a.sourceLinks.length||"target"===this.zD&&0<a.targetLinks.length||
this.zD===gvjs_lb)&&d.Ju(String(b))},this);var k=null;null!=this.lb.wF&&(k=this.lb.wF);var l=this.J.Ua(2);null===l&&(l="Width");var m=null;null!=this.lb.MR&&(m=this.J.Ua(this.lb.MR),null===m&&(m=gvjs_pt));var n=Infinity,p=-Infinity;null!=this.lb.MR&&gvjs_q(a.links,function(a){null!=a.opacity&&(n=Math.min(n,a.opacity),p=Math.max(p,a.opacity))},this);var q=c.pe(),r=h?q:d.pe();gvjs_q(a.links,function(a,b){a.idx=b;var c=this.xna;null!=a.opacity&&p>n&&(c=this.Qca+(a.opacity-n)/(p-n)*(this.qua-this.Qca));
var d=this.fca.clone();d.yf(c);c="source"===this.zD?String(a.source.idx):"target"===this.zD?String(a.target.idx):null;null!=c?d.tf(r.Rq(c)):this.zD===gvjs_lb&&gvjs_3h(d,{ug:r.Rq(String(a.source.idx)),Yf:r.Rq(String(a.target.idx)),Zn:1,$n:1,x1:gvjs_zs,y1:0,x2:gvjs_Cs,y2:0,yo:!0,Mp:!1});c=a.style;null!=c&&(c=gvjs_hJ(c),null!=c&&(c=new gvjs_oi([c]),d.tf(gvjs_Oi(c,[gvjs_Ov,gvjs_fb],d.tb())),d.yf(gvjs_Mi(c,gvjs_Pv,d.ff)),d.Ed(gvjs_Oi(c,[gvjs_0y,gvjs_Db],d.Rf)),gvjs_1h(d,gvjs_Mi(c,gvjs_1y,d.dj)),d.Jl(gvjs_E(c,
gvjs_2y,d.bc))));b=null!=k&&a.ya?{Fi:!(!this.J.getProperty(b,k,gvjs_el)&&!this.J.Cg(k,gvjs_el)),content:a.ya}:{title:a.source.name+" -> "+a.target.name,Jya:l,Lya:a.value,Nda:m,Oda:a.opacity};c=new gvjs_oA;var f=a.source.x0+(a.source.x1-a.source.x0),g=a.source.y0+(a.y0-a.source.y0-a.width/2),h=a.target.x0,q=a.target.y0+(a.y1-a.target.y0-a.width/2),t=(h-f)/3;c.move(f,g);c.bq(f+t,g,f+2*t,q,h,q);c.Aa(h,q+a.width);c.bq(f+2*t,q+a.width,f+t,g+a.width,f,g+a.width);c.close();f=null==this.m.ga(gvjs_d4)?d.clone().yf(.8):
gvjs_Qi(this.m,gvjs_d4,d);g=null==this.m.ga(gvjs_e4)?d.clone().yf(.8):gvjs_Qi(this.m,gvjs_e4,d);h=gvjs_Qi(this.m,gvjs_c4,d);q=null==this.m.ga(gvjs_b4)?d.clone().yf(.2):gvjs_Qi(this.m,gvjs_b4,d);t=gvjs_Qi(this.m,gvjs_e4,f);var u=gvjs_Qi(this.m,gvjs_c4,q);e.push({cc:{Zd:d,selected:f,focused:g,ZL:h,$L:q,$K:t,aM:u},ya:b,uY:a.source.idx,B4:a.target.idx,Nc:c})},this);var t=this.ib.width,u=b.nodeWidth(),v={};gvjs_q(a.nodes,function(a,b){var c=new gvjs_A;gvjs_q(a.sourceLinks,function(a){c.add(a.idx)},this);
gvjs_q(a.targetLinks,function(a){c.add(a.idx)},this);v[b]=c;b=a.x0<t/2;var d=this.dva.clone();d.tf(q.Rq(this.P0===gvjs_Gu?a.Lb:String(a.idx)));d.Ed(d.tb(),0);var e=null==this.m.ga(gvjs_$3)?d.clone().yf(1):gvjs_Qi(this.m,gvjs_$3,d),h=null==this.m.ga(gvjs_a4)?d.clone().yf(1):gvjs_Qi(this.m,gvjs_a4,d),k=gvjs_Qi(this.m,gvjs_93,d),l=null==this.m.ga(gvjs_83)?d.clone().yf(.2):gvjs_Qi(this.m,gvjs_83,d),m=gvjs_Qi(this.m,gvjs_a4,e),n=gvjs_Qi(this.m,gvjs_93,l);g.push({cc:{Zd:d,selected:e,focused:h,ZL:k,$L:l,
$K:m,aM:n},x:a.x0,y:a.y0,ya:a.ya,width:u,height:a.y1-a.y0});d=null==this.m.ga(gvjs_63)?gvjs_ci((new gvjs_bi(this.lf)).setOpacity(.8),!0):gvjs_Ri(this.m,gvjs_63,this.lf);e=null==this.m.ga(gvjs_73)?gvjs_ci((new gvjs_bi(this.lf)).setOpacity(.8),!0):gvjs_Ri(this.m,gvjs_73,this.lf);h=gvjs_Ri(this.m,gvjs_53,this.lf);k=null==this.m.ga(gvjs_43)?(new gvjs_bi(this.lf)).setOpacity(.4):gvjs_Ri(this.m,gvjs_43,this.lf);l=gvjs_Ri(this.m,gvjs_73,d);m=gvjs_Ri(this.m,gvjs_53,k);f.push({angle:0,aA:b?gvjs_2:gvjs_0,bA:gvjs__,
styles:{Zd:this.lf,selected:d,focused:e,ZL:h,$L:k,$K:l,aM:m},text:a.name,width:0,x:b?a.x0+u+this.Pba:a.x0-this.Pba,y:a.y0+(a.y1-a.y0)/2})},this);return{labels:f,paths:e,oS:g,Zta:v,nodeWidth:u,size:this.ib,Oc:this.me,Eg:gvjs_D(this.m,gvjs_gz,!0),Xp:gvjs_Ri(this.m,gvjs_iz)}};function gvjs_wma(a){a=a.lb;return{nodes:a.nodes,links:a.links}}
function gvjs_xma(a){var b=gvjs_r(a.nodes,function(a,b){return{index:b,Zga:[]}});gvjs_q(a.links,function(a){b[a.source].Zga.push(b[a.target])});a=new gvjs_A(b);for(var c=new gvjs_A,d=0;0<a.Eb();){if(d>b.length)throw a=gvjs_r(a.Ra(),function(a){return a.index}).join(","),Error("Cycle found in rows: "+a);gvjs_q(a.Ra(),function(a){gvjs_q(a.Zga,function(a){c.add(a)})});a=c;c=new gvjs_A;d++}}
function gvjs_yma(a){gvjs_q(a,function(a){gvjs_1c(a.targetLinks,function(a,b){function c(a){return(a.target.y0-(a.source.y0+(a.y0-a.source.y0-a.width/2)))/(a.target.x0-a.source.x0)}return c(b)-c(a)})});gvjs_q(a,function(a){var b=0;gvjs_q(a.targetLinks,function(a){a.y1=b+a.target.y0+a.width/2;b+=a.width})})};function gvjs_i4(a){gvjs_2M.call(this,a)}gvjs_p(gvjs_i4,gvjs_2M);gvjs_=gvjs_i4.prototype;gvjs_.Lq=function(){return{NAME:gvjs_Ax}};
gvjs_.Ih=function(){return{backgroundColor:{fill:gvjs_Qb,stroke:gvjs_6a,strokeWidth:10,strokeOpacity:.2},tooltip:{isHtml:!1,textStyle:{fontName:gvjs__s,fontSize:16,color:gvjs_6a}},sankey:{iterations:32,link:{colorMode:gvjs_d,color:{fill:"#aaa",fillOpacity:.8,stroke:gvjs_d},defaultOpacity:.6,minOpacity:.2,maxOpacity:.6},node:{colorMode:gvjs_33,color:{fill:gvjs_6a,fillOpacity:.8},label:{fontName:gvjs_zb,fontSize:10,color:gvjs_7r,bold:!1,italic:!1},labelPadding:6,nodePadding:10,width:10,interactivity:!1,
selectionMode:gvjs_Ly}}}};gvjs_.Oo=function(a,b){return new gvjs_f4(a,b)};gvjs_.sn=function(a,b,c,d){return new gvjs_h4(a,b,c,d)};gvjs_.uq=function(a,b,c,d){a=gvjs_i4.o.uq.call(this,a,b,c,d);a.Nw([gvjs_oy,gvjs_VT,gvjs_ny,gvjs_RT,gvjs_Ft,gvjs_Et,gvjs_0l]);return a};
gvjs_.Ks=function(a){var b=gvjs_D(a,"sankey.node.interactivity",!1),c=[new gvjs_gU([new gvjs_OM(gvjs_qt)]),new gvjs_jU([new gvjs_OM(gvjs_qt)])];b&&c.push(new gvjs_iU([gvjs_QM(new gvjs_OM(gvjs_qt),gvjs_ut,"node")]));gvjs_D(a,"sankey.link.interactivity",!1)&&(a=gvjs_C(a,"sankey.link.selectionMode",gvjs_Ly)===gvjs_Ly,c.push(new gvjs_hU([gvjs_QM(new gvjs_OM(gvjs_qt),gvjs_ut,"link")],a)));return c};gvjs_k(gvjs_1k,gvjs_i4,void 0);gvjs_i4.prototype.draw=gvjs_i4.prototype.draw;gvjs_i4.prototype.setSelection=gvjs_i4.prototype.setSelection;gvjs_i4.prototype.getSelection=gvjs_i4.prototype.getSelection;gvjs_i4.prototype.clearChart=gvjs_i4.prototype.Wb;gvjs_i4.prototype.getContainer=gvjs_i4.prototype.getContainer;
